### ISSUE TITLE
show days left instead of percentage

### ISSUE THREAD

**Issue by wunschadresse** [rickybas/date-countdown#8]
Hi and thanks for your date-countdown application!

I like it very much, but sometimes I am not so much interested in the time span or percentage that has passed, since I entered a countdown, but more simply in the days that are left until that deadline. 
I know that in your app it does show the days remaining (and spent), but I would like to see that highlighted.

So here is my idea: 

Allow for the option _not_ to set a start date.
Then display the remaining days in the field where it now shows the percentage. 
May be visualize the last remaining 4-8 days with the circular bar (or enter an exponential function so that the bar progresses faster as it moves towards the deadline)

That would be very nice, especially as I could not find any other application in the linux repository that offers this function (apart from timer-applet ?which only runs on unity?, and i am using elementary'OS)

Coming to think of it:
Leaving out the End Date could give the option of simply counting days passed that I have been working on a project.

cheerios.

**Comment by rickybassom** [comment]
Firstly apologies for not replying sooner, I have been busy with school.

The reason I put the percentage in the circle, as apposed to the days remaining, is because the number of character will always be 2 to 4 therefore I don't have to do any text scaling. Having the days remaining will mean that there could be an infinite number of characters in the circle which means that I have to use text scaling to fit them in.

The start date is set as the current day as default.

An exponential function is likely to confuse the user.

I think that having the percentage to represent the whole time period will be more suitable for more use cases.

Having a counting days system is out of the scope of this project and the name "date countdown".

However, feel free to fork it if you want and create your own variation.

Thank you for your interest in this project.
