### ISSUE TITLE
Remove button in the context menu does not work.

### ISSUE THREAD

**Issue by level6sam** [rickybas/date-countdown#9]
When right clicking for more options. I am unable to remove a count down timer. The remove button is unresponsive on click. The only other alternatives are to save the current timer or click on the applets pane.

**Comment by rickybassom** [comment]
Thank you for pointing out this bug.

I remember having this problem in development. It was caused by the gtk popover going outside the master window and therefore the parts out of the window in the popover becomes unresponsive because elementary uses xorg (an issue I don't have as I use fedora wayland).

I could solve this by making the master window larger or turning the popover into a dialog window. But I think the popover is much more elegant.

**Comment by level6sam** [comment]
Hello Ricky,

Thanks for the reply. I think the extension of the master window would be preferable and a more elegant solution. Not being able to click on something which is unresponsive is really annoying.

Regards,

Sampath
